# Generated by Django 4.2.2 on 2023-07-11 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_place_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_subcategory',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_category'),
        ),
    ]
