# Generated by Django 4.2.2 on 2023-09-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_subcategory_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_product_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=50)),
            ],
        ),
    ]
