# Generated by Django 4.2.2 on 2023-07-24 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_alter_tbl_shopregistration_shop_proof'),
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_product',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_shopregistration'),
        ),
    ]
