# Generated by Django 4.2.2 on 2023-07-24 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_subcategory_category'),
        ('Shop', '0003_rename_subcategory_tbl_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_product',
            name='category',
        ),
        migrations.AddField(
            model_name='tbl_product',
            name='subcat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_subcategory'),
        ),
    ]
