# Generated by Django 4.2.2 on 2023-07-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_remove_tbl_product_category_tbl_product_subcat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_product',
            name='product_details',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='tbl_product',
            name='product_rate',
            field=models.CharField(max_length=50),
        ),
    ]
