# Generated by Django 4.2.2 on 2023-07-24 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_tbl_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_gallery',
            old_name='Cation',
            new_name='cation',
        ),
    ]
