# Generated by Django 4.2.2 on 2023-09-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_rename_cation_tbl_gallery_cation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_product',
            name='product_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
