# Generated by Django 4.2.2 on 2023-09-06 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_tbl_product_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_product',
            name='product_type',
        ),
    ]
