# Generated by Django 4.2.2 on 2023-09-06 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_product_type'),
        ('Shop', '0009_remove_tbl_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_product',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_product_type'),
        ),
    ]
