# Generated by Django 4.2.2 on 2023-07-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_userregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_contact', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_address', models.CharField(max_length=50)),
                ('user_gender', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
