# Generated by Django 4.2.2 on 2023-07-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_tbl_userregister_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_userregister',
            name='user_photo',
            field=models.FileField(null=True, upload_to='userdocs/'),
        ),
    ]
