# Generated by Django 4.2.2 on 2023-07-14 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_subcategory_category'),
        ('Guest', '0003_tbl_userregister_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_shopregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=50)),
                ('shop_contact', models.CharField(max_length=50)),
                ('shop_email', models.EmailField(max_length=254, unique=True)),
                ('shop_address', models.CharField(max_length=100)),
                ('shop_logo', models.FileField(null=True, upload_to='shopdocs/')),
                ('shop_proof', models.FileField(null=True, upload_to='shopfroof/')),
                ('shop_since', models.CharField(max_length=50)),
                ('shop_password', models.CharField(max_length=50, unique=True)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
