# Generated by Django 4.2.2 on 2023-07-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_shopregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_shopregistration',
            name='shop_proof',
            field=models.FileField(null=True, upload_to='shopproof/'),
        ),
    ]
