# Generated by Django 4.2.2 on 2023-08-23 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_alter_tbl_shopregistration_shop_proof'),
        ('User', '0003_tbl_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_complaint',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_userregister'),
        ),
    ]
