# Generated by Django 4.2.2 on 2023-08-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_tbl_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_feedback',
            name='feedback_date',
            field=models.DateField(auto_now=True),
        ),
    ]
