# Generated by Django 4.2.2 on 2023-08-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_tbl_feedback_feedback_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_complaint',
            name='complaint_reply',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
