# Generated by Django 4.2.2 on 2023-08-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_tbl_complaint_complaint_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_complaint',
            name='complaint_reply',
            field=models.CharField(default='No Reply yet', max_length=100),
        ),
    ]
