# Generated by Django 4.2.2 on 2023-09-04 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_alter_tbl_shopregistration_shop_proof'),
        ('User', '0009_alter_tbl_complaint_complaint_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_complaint',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_shopregistration'),
        ),
        migrations.AddField(
            model_name='tbl_feedback',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_shopregistration'),
        ),
    ]
