# Generated by Django 4.2.2 on 2023-09-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_tbl_complaint_shop_tbl_feedback_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_complaint',
            name='complaint_status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
